services:
  generator-web:
    build:
      context: .
      dockerfile: generator-web/Dockerfile
    container_name: generator-web
    ports:
      - "8090:8090"

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: somedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_SCHEMA: public
      SERVER_HTTP_PORT: "7704"
    ports:
      - "7704:7704"

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: somedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_SCHEMA: public
      SERVER_HTTP_PORT: "7705"
    ports:
      - "7705:7705"

  traefik:
    image: traefik:v3.1
    container_name: micro-traefik
    depends_on:
      - generator-web
      - auth-service
      - user-service
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "8000:8000"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
