services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: belajarmudah
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_SCHEMA: public
      SERVER_HTTP_PORT: "7704"
    ports:
      - "7704:7704"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.auth-service.loadbalancer.server.port=7704"
      - "traefik.http.routers.auth-login.rule=Path(`/api/v1/login`)"
      - "traefik.http.routers.auth-login.entrypoints=web"
      - "traefik.http.routers.auth-login.middlewares=auth-strip-v1,auth-addprefix,public-common@file"
      - "traefik.http.routers.auth-login.service=auth-service"
      - "traefik.http.routers.auth-api.rule=PathPrefix(`/api/v1/auth`)"
      - "traefik.http.routers.auth-api.entrypoints=web"
      - "traefik.http.routers.auth-api.middlewares=auth-strip-v1,auth-addprefix,protected-common@file"
      - "traefik.http.routers.auth-api.service=auth-service"
      - "traefik.http.middlewares.auth-strip-v1.stripprefix.prefixes=/api/v1"
      - "traefik.http.middlewares.auth-addprefix.addprefix.prefix=/api/auth-service/v1"

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: belajarmudah
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_SCHEMA: public
      SERVER_HTTP_PORT: "7705"
    ports:
      - "7705:7705"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.user-service.loadbalancer.server.port=7705"
      - "traefik.http.routers.user-api.rule=PathPrefix(`/api/v1/user`)"
      - "traefik.http.routers.user-api.entrypoints=web"
      - "traefik.http.routers.user-api.middlewares=user-strip-v1,user-addprefix,protected-common@file"
      - "traefik.http.routers.user-api.service=user-service"
      - "traefik.http.middlewares.user-strip-v1.stripprefix.prefixes=/api/v1"
      - "traefik.http.middlewares.user-addprefix.addprefix.prefix=/api/user-service/v1"

  traefik:
    image: traefik:v3.1
    container_name: micro-traefik
    depends_on:
      - auth-service
      - user-service
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "8000:8000"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
